
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Apr 10 2026 08:30:00 +07 (Apr 10 2026 01:30:00 UTC)

// Verification Directory fv/bound_flasher 

module bound_flasher(lamp, clk, rst_n, flick);
  input clk, rst_n, flick;
  output [15:0] lamp;
  wire clk, rst_n, flick;
  wire [15:0] lamp;
  wire [3:0] state;
  wire n_5, n_17, n_19, n_21, n_22, n_23, n_24, n_25;
  wire n_32, n_34, n_36, n_37, n_39, n_43, n_45, n_48;
  wire n_50, n_51, n_53, n_54, n_55, n_56, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_102, n_104, n_105, n_106, n_108, n_109, n_110, n_111;
  wire n_112, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_134, n_135, n_136;
  wire n_137, n_138, n_139, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_150, n_151, n_152;
  wire n_153, n_154, n_155, n_156, n_158, n_159, n_160, n_161;
  wire n_165;
  OAI2BB1X1 g5418__2398(.A0N (n_159), .A1N (n_114), .B0 (n_160), .Y
       (n_161));
  AOI221X1 g5423__5107(.A0 (state[1]), .A1 (n_59), .B0 (n_159), .B1
       (n_97), .C0 (n_154), .Y (n_160));
  OAI221X1 g5415__6260(.A0 (n_105), .A1 (n_117), .B0 (n_70), .B1
       (flick), .C0 (n_156), .Y (n_158));
  DFFRHQX1 \state_reg[3] (.RN (rst_n), .CK (clk), .D (n_150), .Q
       (state[3]));
  AOI22X1 g5425__8428(.A0 (n_140), .A1 (flick), .B0 (n_149), .B1
       (n_61), .Y (n_156));
  OAI221X1 g5419__5526(.A0 (n_128), .A1 (n_151), .B0 (n_110), .B1
       (n_152), .C0 (n_104), .Y (n_155));
  INVX1 g5429(.A (n_148), .Y (n_154));
  OAI222X1 g5420__6783(.A0 (n_43), .A1 (n_152), .B0 (n_129), .B1
       (n_139), .C0 (n_144), .C1 (n_151), .Y (n_153));
  OAI33X1 g5431__3680(.A0 (n_149), .A1 (n_62), .A2 (n_63), .B0 (n_95),
       .B1 (n_120), .B2 (n_86), .Y (n_150));
  AOI33XL g5432__1617(.A0 (n_149), .A1 (n_21), .A2 (n_146), .B0 (n_91),
       .B1 (n_93), .B2 (n_141), .Y (n_148));
  OAI2BB1X1 g5424__2802(.A0N (lamp[0]), .A1N (n_127), .B0 (n_146), .Y
       (n_147));
  OAI222X1 g5430__1705(.A0 (n_144), .A1 (n_152), .B0 (n_81), .B1
       (n_115), .C0 (n_74), .C1 (n_151), .Y (n_145));
  DFFRHQX1 \lamp_reg[2] (.RN (rst_n), .CK (clk), .D (n_124), .Q
       (lamp[2]));
  DFFRHQX1 \lamp_reg[8] (.RN (rst_n), .CK (clk), .D (n_138), .Q
       (lamp[8]));
  OAI31X1 g5441__5122(.A0 (lamp[1]), .A1 (n_131), .A2 (n_87), .B0
       (n_119), .Y (n_143));
  DFFRHQX1 \lamp_reg[15] (.RN (rst_n), .CK (clk), .D (n_118), .Q
       (lamp[15]));
  OAI211X1 g5426__8246(.A0 (n_89), .A1 (n_76), .B0 (state[1]), .C0
       (n_141), .Y (n_142));
  NAND2BX1 g5445__7098(.AN (n_39), .B (n_122), .Y (n_140));
  AOI221X1 g5427__6131(.A0 (lamp[7]), .A1 (n_58), .B0 (n_77), .B1
       (n_94), .C0 (n_78), .Y (n_139));
  OAI22X1 g5468__1881(.A0 (n_25), .A1 (n_152), .B0 (n_36), .B1 (n_151),
       .Y (n_138));
  OAI2BB1X1 g5461__5115(.A0N (lamp[8]), .A1N (n_135), .B0 (n_106), .Y
       (n_137));
  OAI2BB1X1 g5462__7482(.A0N (lamp[2]), .A1N (n_135), .B0 (n_100), .Y
       (n_136));
  OAI2BB1X1 g5463__4733(.A0N (lamp[10]), .A1N (n_135), .B0 (n_108), .Y
       (n_134));
  OAI22X1 g5465__6161(.A0 (n_34), .A1 (n_152), .B0 (n_73), .B1 (n_151),
       .Y (n_133));
  OAI22X1 g5467__9315(.A0 (n_111), .A1 (n_152), .B0 (n_54), .B1
       (n_151), .Y (n_132));
  NOR3X1 g5459__9945(.A (lamp[1]), .B (n_98), .C (n_131), .Y (n_149));
  OAI22X1 g5457__2883(.A0 (n_129), .A1 (n_152), .B0 (n_71), .B1
       (n_151), .Y (n_130));
  AOI21X1 g5444__2346(.A0 (lamp[10]), .A1 (n_92), .B0 (lamp[11]), .Y
       (n_128));
  OAI21X1 g5446__1666(.A0 (n_131), .A1 (state[1]), .B0 (n_99), .Y
       (n_127));
  OAI2BB1X1 g5451__7410(.A0N (lamp[15]), .A1N (n_135), .B0 (n_102), .Y
       (n_126));
  OAI2BB1X1 g5455__6417(.A0N (lamp[14]), .A1N (n_135), .B0 (n_112), .Y
       (n_125));
  OAI22X1 g5456__5477(.A0 (n_22), .A1 (n_152), .B0 (n_50), .B1 (n_151),
       .Y (n_124));
  OAI22X1 g5469__2398(.A0 (n_24), .A1 (n_152), .B0 (n_84), .B1 (n_151),
       .Y (n_123));
  OR2X1 g5460__5107(.A (n_116), .B (n_90), .Y (n_122));
  OAI211X1 g5464__6260(.A0 (n_120), .A1 (n_53), .B0 (lamp[1]), .C0
       (n_146), .Y (n_121));
  AOI22X1 g5466__4319(.A0 (lamp[1]), .A1 (n_135), .B0 (lamp[0]), .B1
       (n_109), .Y (n_119));
  NOR2X1 g5477__8428(.A (n_37), .B (n_151), .Y (n_118));
  AOI211XL g5442__5526(.A0 (lamp[6]), .A1 (n_23), .B0 (n_96), .C0
       (n_116), .Y (n_117));
  INVX1 g5450(.A (n_141), .Y (n_115));
  OAI221X1 g5443__6783(.A0 (lamp[6]), .A1 (flick), .B0 (lamp[11]), .B1
       (n_68), .C0 (n_83), .Y (n_114));
  OAI2BB1X1 g5478__3680(.A0N (n_111), .A1N (n_110), .B0 (n_109), .Y
       (n_112));
  OAI21X1 g5484__1617(.A0 (lamp[8]), .A1 (lamp[9]), .B0 (n_109), .Y
       (n_108));
  OAI2BB1X1 g5481__2802(.A0N (n_43), .A1N (n_144), .B0 (n_109), .Y
       (n_106));
  NOR2X1 g5458__1705(.A (n_116), .B (n_105), .Y (n_141));
  NAND2X1 g5452__5122(.A (lamp[10]), .B (n_88), .Y (n_104));
  OAI21X1 g5487__8246(.A0 (lamp[13]), .A1 (lamp[14]), .B0 (n_109), .Y
       (n_102));
  OAI2BB1X1 g5486__7098(.A0N (n_99), .A1N (n_98), .B0 (n_109), .Y
       (n_100));
  OR3X1 g5453__6131(.A (n_96), .B (n_95), .C (n_48), .Y (n_97));
  OAI21X1 g5454__1881(.A0 (n_93), .A1 (flick), .B0 (n_85), .Y (n_94));
  OR4X1 g5470__5115(.A (n_45), .B (n_55), .C (n_67), .D (n_95), .Y
       (n_92));
  NAND2BX1 g5476__7482(.AN (n_75), .B (n_91), .Y (n_131));
  NAND3X1 g5485__4733(.A (n_89), .B (state[1]), .C (n_146), .Y (n_90));
  INVX1 g5483(.A (n_135), .Y (n_152));
  INVX1 g5491(.A (n_109), .Y (n_151));
  OAI222X1 g5474__6161(.A0 (state[1]), .A1 (n_87), .B0 (n_86), .B1
       (flick), .C0 (n_110), .C1 (n_65), .Y (n_88));
  NOR4BX1 g5473__9315(.AN (n_84), .B (lamp[8]), .C (n_72), .D (n_82),
       .Y (n_85));
  OAI21X1 g5475__9945(.A0 (n_79), .A1 (n_66), .B0 (lamp[11]), .Y
       (n_83));
  OR2X1 g5471__2883(.A (n_82), .B (n_95), .Y (n_116));
  MX2X1 g5489__2346(.A (n_80), .B (n_81), .S0 (n_144), .Y (n_96));
  OR3X1 g5488__1666(.A (n_24), .B (n_80), .C (n_79), .Y (n_120));
  OR3X1 g5490__7410(.A (n_56), .B (n_60), .C (n_64), .Y (n_135));
  OR2XL g5497__6417(.A (n_78), .B (n_77), .Y (n_109));
  AND2X1 g5479__5477(.A (n_91), .B (flick), .Y (n_76));
  NAND3BXL g5480__2398(.AN (n_82), .B (n_74), .C (n_73), .Y (n_75));
  NOR2X1 g5494__5107(.A (n_144), .B (n_80), .Y (n_89));
  OR2X1 g5482__6260(.A (n_129), .B (n_72), .Y (n_95));
  INVX1 g5510(.A (n_86), .Y (n_78));
  NOR2X1 g5518__4319(.A (lamp[3]), .B (lamp[4]), .Y (n_71));
  NAND2X1 g5493__8428(.A (state[1]), .B (n_77), .Y (n_70));
  NOR2X1 g5492__5526(.A (lamp[12]), .B (n_67), .Y (n_68));
  NOR2X1 g5495__6783(.A (lamp[6]), .B (n_81), .Y (n_91));
  OR3X1 g5514__3680(.A (state[0]), .B (n_66), .C (n_65), .Y (n_86));
  AOI21X1 g5500__1617(.A0 (n_63), .A1 (n_65), .B0 (n_62), .Y (n_64));
  AO21X1 g5499__2802(.A0 (n_66), .A1 (n_159), .B0 (n_60), .Y (n_61));
  MX2X1 g5498__1705(.A (n_146), .B (n_58), .S0 (lamp[11]), .Y (n_59));
  OR4X1 g5504__5122(.A (n_19), .B (n_110), .C (n_144), .D (n_32), .Y
       (n_79));
  OR3X1 g5512__8246(.A (n_25), .B (n_17), .C (n_55), .Y (n_80));
  NAND2BX1 g5496__7098(.AN (n_67), .B (n_54), .Y (n_82));
  OR4X1 g5502__6131(.A (n_22), .B (n_129), .C (n_51), .D (n_93), .Y
       (n_53));
  OR4X1 g5503__1881(.A (n_99), .B (n_98), .C (n_22), .D (n_51), .Y
       (n_72));
  INVX1 g5506(.A (n_77), .Y (n_87));
  NOR2X1 g5507__5115(.A (n_66), .B (n_105), .Y (n_56));
  NOR2X1 g5516__7482(.A (lamp[1]), .B (lamp[2]), .Y (n_50));
  NOR2X1 g5527__4733(.A (lamp[11]), .B (state[0]), .Y (n_48));
  NAND2X1 g5530__6161(.A (lamp[6]), .B (lamp[9]), .Y (n_45));
  AOI211XL g5501__9315(.A0 (n_144), .A1 (state[0]), .B0 (state[1]), .C0
       (n_5), .Y (n_39));
  AND2X1 g5511__9945(.A (n_93), .B (n_146), .Y (n_60));
  NAND2X1 g5508__2883(.A (n_111), .B (n_37), .Y (n_67));
  NAND2X1 g5513__2346(.A (n_36), .B (n_84), .Y (n_81));
  AND2X1 g5509__1666(.A (n_66), .B (n_58), .Y (n_77));
  NOR2X1 g5520__7410(.A (lamp[4]), .B (lamp[5]), .Y (n_74));
  NAND2X1 g5521__6417(.A (lamp[7]), .B (lamp[8]), .Y (n_55));
  NOR2X1 g5523__5477(.A (lamp[2]), .B (lamp[3]), .Y (n_73));
  INVX1 g5515(.A (n_58), .Y (n_105));
  INVX1 g5526(.A (n_159), .Y (n_65));
  NAND2X1 g5529__2398(.A (lamp[13]), .B (lamp[15]), .Y (n_32));
  NAND2X1 g5528__5107(.A (n_66), .B (flick), .Y (n_23));
  NOR2X1 g5533__6260(.A (lamp[14]), .B (lamp[15]), .Y (n_37));
  NOR2X1 g5534__4319(.A (lamp[11]), .B (lamp[12]), .Y (n_54));
  NAND2X1 g5532__8428(.A (n_21), .B (n_66), .Y (n_62));
  NOR2X1 g5535__5526(.A (lamp[9]), .B (lamp[10]), .Y (n_84));
  NOR2X1 g5524__3680(.A (state[3]), .B (n_66), .Y (n_146));
  NAND2X1 g5519__1617(.A (lamp[2]), .B (lamp[4]), .Y (n_51));
  NOR2X1 g5522__2802(.A (lamp[7]), .B (lamp[8]), .Y (n_36));
  NAND2X1 g5531__1705(.A (state[3]), .B (n_93), .Y (n_63));
  OR2X1 g5517__8246(.A (state[2]), .B (state[3]), .Y (n_5));
  DFFRX1 \lamp_reg[11] (.RN (rst_n), .CK (clk), .D (n_155), .Q
       (lamp[11]), .QN (n_24));
  DFFRX1 \lamp_reg[7] (.RN (rst_n), .CK (clk), .D (n_137), .Q
       (lamp[7]), .QN (n_43));
  DFFRX1 \lamp_reg[9] (.RN (rst_n), .CK (clk), .D (n_134), .Q
       (lamp[9]), .QN (n_25));
  DFFRX1 \lamp_reg[4] (.RN (rst_n), .CK (clk), .D (n_130), .Q
       (lamp[4]), .QN (n_34));
  DFFRX1 \lamp_reg[14] (.RN (rst_n), .CK (clk), .D (n_126), .Q
       (lamp[14]), .QN (n_19));
  DFFRX1 \lamp_reg[10] (.RN (rst_n), .CK (clk), .D (n_123), .Q
       (lamp[10]), .QN (n_17));
  DFFRX1 \lamp_reg[3] (.RN (rst_n), .CK (clk), .D (n_133), .Q
       (lamp[3]), .QN (n_22));
  DFFRX1 \lamp_reg[0] (.RN (rst_n), .CK (clk), .D (n_143), .Q
       (lamp[0]), .QN (n_98));
  DFFRX1 \state_reg[0] (.RN (rst_n), .CK (clk), .D (n_158), .Q
       (state[0]), .QN (n_21));
  DFFRX1 \lamp_reg[1] (.RN (rst_n), .CK (clk), .D (n_136), .Q
       (lamp[1]), .QN (n_99));
  DFFRX1 \lamp_reg[13] (.RN (rst_n), .CK (clk), .D (n_125), .Q
       (lamp[13]), .QN (n_111));
  DFFRX1 \lamp_reg[12] (.RN (rst_n), .CK (clk), .D (n_132), .Q
       (lamp[12]), .QN (n_110));
  DFFRX1 \lamp_reg[5] (.RN (rst_n), .CK (clk), .D (n_145), .Q
       (lamp[5]), .QN (n_129));
  DFFRX1 \state_reg[1] (.RN (rst_n), .CK (clk), .D (n_161), .Q
       (state[1]), .QN (n_93));
  DFFRX1 \lamp_reg[6] (.RN (rst_n), .CK (clk), .D (n_153), .Q
       (lamp[6]), .QN (n_144));
  DFFRX1 \state_reg[2] (.RN (rst_n), .CK (clk), .D (n_165), .Q
       (state[2]), .QN (n_66));
  NAND4BX1 g2(.AN (n_56), .B (n_121), .C (n_147), .D (n_142), .Y
       (n_165));
  NOR2X1 g5536__5646(.A (state[3]), .B (n_93), .Y (n_159));
  NOR2X1 g5525__5648(.A (state[3]), .B (n_21), .Y (n_58));
endmodule

